### ISSUE TITLE
[JOSS Review] Include source code for documentation. 

### ISSUE THREAD

**Issue by melund** [0todd0000/mwarp1d#3]
Where is the source code for the documentation? I think it would be good practice if the sphinx source code for the documentation lived in the repository.

Contributing to documentation is also big part of "open source", and it would allow you automatically build the documentation with a CI service like github actions.

**Comment by 0todd0000** [comment]
Good idea, sorry about that!
All Sphinx source code has been uploaded to the [gh-pages](https://github.com/0todd0000/mwarp1d/tree/gh-pages) branch.

**Comment by melund** [comment]
Nice. I didn't know gh-pages could also build sphinx documentation. 

Just keep in mind that having docs in a separate branch can make it a little more difficult to sync source and documentation. It is not a blocker for the review but you could move the docs source  into a docs/ subfolder in the main repository. You can still exclude the docs source when you build pypi and conda packages. 

I think gh-pages can also handle that the [docs is located in a sub folder](https://www.docslikecode.com/articles/github-pages-python-sphinx/)  in the main branch..

**Comment by melund** [comment]
I think I can close this. My remaining comments are not blockers.
